### ISSUE TITLE
Worlds first issue and worlds most intelligent opensource bots in Chinese!

### ISSUE THREAD

**Issue by lucasjinreal** [OpenBuddy/OpenBuddy#1]
Hello, after testing, this robot is much more advanced than other methods, may I ask further 2 questions?
1. can u share some more details on model/data training details?
2. does there a llama.cpp deploy guidance? I'd like try inference on local CPU as GPU assumes too many mem, in my experience, my 32GB macbook pro can run 13B model in realtime! (int4)

**Comment by 44670** [comment]
Thank you for your kind words.

Regarding your first question, due to the nature of our ongoing exploratory process, we're not in a position to provide specific details about our model training and data practices at this time. We are experimenting with a variety of methods and datasets to further enhance the performance of our models.

Regarding your second question, you can follow the guide on this page: https://github.com/OpenBuddy/OpenBuddy#usage-with-llamacpp-on-cpu-recommended . While we haven't specifically tested this on a macOS, we anticipate that you would need at least 16GB of memory or more. Please note that this is an estimation, and your mileage may vary depending on the specific details of your system and application.

Again, thank you for your support and interest in our work. We're excited to see how you use our models!

**Comment by lucasjinreal** [comment]
thank u! will try it.

**Comment by 44670** [comment]
13B is available to Early Access testers for now. More info could be found at: https://github.com/OpenBuddy/OpenBuddy/blob/main/models.md

**Comment by lucasjinreal** [comment]
@44670 thanks! I have applied an access, hope can get a chance to test

**Comment by 44670** [comment]
Hi, it looks like the huggingface ID you provided in the form could not be found.

We need to add your huggingface ID into the Early Access organization for allowing you to access our 13B models.

**Comment by lucasjinreal** [comment]
@44670 hello, I thought it was same as my github id, turned out it was :

<img width="311" alt="image" src="https://github.com/OpenBuddy/OpenBuddy/assets/21303438/1656db4c-a5be-4d77-8363-9b085ed915a1">

please add me, thanks a lot!

**Comment by 44670** [comment]
Hi, you have been invited.

Feel free to access our 13B models: https://huggingface.co/organizations/OpenBuddyEA
