### ISSUE TITLE
不表达任何意思，但是我想让开发者看看这个文章，难受

### ISSUE THREAD

**Issue by Notingnoone** [OpenBuddy/OpenBuddy#36]
https://tenclass.com.cn/news/news104/
不表达任何意思，但是我想让开发者看看这个文章，难受

**Comment by 44670** [comment]
I have reviewed the article in question. WeiKe Software indeed provided assistance in terms of computational resources during the training phase, and this has been acknowledged in our README.md. The inaccuracies in the article might be due to misunderstandings from the corporate publicity department, so there's no need to be overly concerned about it.
